### ISSUE TITLE
Error after npm start from Windows

### ISSUE THREAD

**Issue by chromilo** [dottymatrix/Kora#1]
Must be because I use Windows. 
---
Module not found: Error: Can't resolve './Login'. 
![image](https://github.com/dottymatrix/Kora/assets/75153964/8bd5b113-c746-42f9-8840-2da6a25f626a)

**Comment by dottymatrix** [comment]
t's been a while since I touched it. It's the pages that have issues. They need to either be routed or created.
I went away to work on ML issues(so far able to communicate with Spotify API in Colab, if logic works, I won't spend much time on training) and @vaishnavi-3969  is working on the app as well. If you want to join and deploy the homepage Frontend and Okta identity auth /management, you can do that on a different branch for now. 

Design guide
![Design guidelines sample](https://github.com/dottymatrix/Kora/assets/102636953/22b192d8-c4a5-435d-8623-d1dfcaca4244)

The home page design with generated playlist thumbnails
![Home](https://github.com/dottymatrix/Kora/assets/102636953/a9dd211c-67c7-4b5d-a643-3969de426864)

If you can help out that'll be great! We need to integrate Okta - They have their own login system and they let you customise it so we can have it according to our designs. The logo is in the public folder.

**Comment by dottymatrix** [comment]
@chromilo  If you want to work on Okta Auth, It would be useful to integrate login with Spotify only( that's where our ML model get's data from)

**Comment by chromilo** [comment]
Ok, working on a branch. I have the okta auth working on my dev tenant. Can you elaborate "integrate login with Spotify only"? Just want to make sure I understand. Okta will still be our Idp, the OIDC app is the Kora app. Where would Spotify fit? Also can you please add me to the DevPost submission? I don't see it. Thanks

**Comment by dottymatrix** [comment]
> Ok, working on a branch. I have the okta auth working on my dev tenant. Can you elaborate "integrate login with Spotify only"? Just want to make sure I understand. Okta will still be our Idp, the OIDC app is the Kora app. Where would Spotify fit? Also can you please add me to the DevPost submission? I don't see it. Thanks

Hello Chromilo, Please send you devpost email on discord here @abisoye_o#0. 

That sounds great, thanks for stepping in to get us closer to deploying. Correct Okta is Identity provider. Right now, we have a playlist generator, but it does not have any model behind it. I'm working on that and my dataset is 60% downloaded. The logic is also written. If you're curious it's the spotify 1M playlist dataset.

Here's a better way to explain why we're using Spotify. I just got back from a break and am too tired to break everything down. Bing is able to do it since it knows some of the workflow I've been in and out of today: 

### Kora
Our playlist generator app, is a web application that uses machine learning to create personalized playlists for Spotify users based on their profile and activity data. To access this data, we need to use the Spotify Login authentication, which is an implementation of the **OpenID Connect (OIDC) protocol**. OIDC is a standard for identity verification and authorization that allows us to securely obtain the user's identity, preferences, and permissions from Spotify.

However, **Spotify Login authentication** only handles the user's identity and access to Spotify resources, not the user's account and profile on our app. To manage the user's account and profile on our app, we need to use the Okta Auth service, which is a cloud-based platform that provides user management and authentication solutions. Okta Auth supports both **OIDC and SCIM (System for Cross-domain Identity Management) protocols**, which allow us to synchronize the user's identity and profile data between Spotify and our app.

By bringing **Okta OIDC and SCIM together** with Spotify Login, we can achieve the following benefits:

- We can provide a seamless and secure user experience, as the user only needs to log in once with their Spotify credentials, and we can automatically create and update their account and profile on our app.
- We can leverage the user's profile and dataset from Spotify to train and evaluate our machine learning model, and generate playlists that match the user's preferences and **Spotify profile**.
- We can store and manage the user's data on our app, such as the generated playlists (this is out of scope, but ratings as well)

**Comment by chromilo** [comment]
my email is chromiloamin@gmail.com. I sent you a discord ping, my discord handle is @tarrdawg. My devpost site is https://devpost.com/chromilo
